# ported from hero
controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    omni_chassis_controller:
      type: meta_chassis_controller/OmniChassisController

    wheels_pid_controller:
      type: pid_controller/PidController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

omni_chassis_controller:
  ros__parameters:
    omni_wheel_joints:
      - wheels_pid_controller/front_left_wheel_joint
      - wheels_pid_controller/front_right_wheel_joint
      - wheels_pid_controller/back_left_wheel_joint
      - wheels_pid_controller/back_right_wheel_joint

    omni_wheel_forward_angles: [0.0, 180.0, 0.0, 180.0]

    omni_wheel_center_x: [0.2, 0.2, -0.2, -0.2]
    omni_wheel_center_y: [0.2, -0.2, 0.2, -0.2]

    omni_wheel_sliding_angles: [-45.0, 45.0, 45.0, -45.0]

    omni_wheel_radius: 0.076

    control_mode: 0

    yaw_gimbal_joint: dummy_yaw_wheel_joint

    follow_pid_gains:
      { p: 4.0, i: 2.0e-1, d: 0.0, i_clamp_max: 3.0, i_clamp_min: -3.0, antiwindup: true }

    follow_pid_target: 0.0

    reference_timeout: 0.2

wheels_pid_controller:
  ros__parameters:
    dof_names:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint

    command_interface: effort

    reference_and_state_interfaces: ["velocity"]

    gains:
      front_left_wheel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      front_right_wheel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      back_left_wheel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      back_right_wheel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }

dbus_control_node:
  ros__parameters:
    dbus_port: "ttyUSB0"

hero_vehicle:
  ros__parameters:
    enable_ros2_control: true
    aim_topic: "/gimbal_position_controller/reference"
    shoot_topic: "/shoot_controller/reference"
    control:
      trans_vel: 2.5 # m/s
      rot_vel: 3.0 # rad/s
      stick_sens: 5.00 # rad/s
      mouse_sens: 10.0
      deadzone: 0.3 # percentage
      video_link_blank_time: 0.05 # second