controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    omni_chassis_controller:
      type: meta_chassis_controller/OmniChassisController

    wheels_pid_controller:
      type: pid_controller/PidController

    gimbal_position_controller:
      type: meta_gimbal_controller/GimbalPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    shoot_controller:
      type: meta_shoot_controller/ShootController
    
    forward_pitch_controller:
        type: forward_command_controller/ForwardCommandController
    forward_yaw_controller:
        type: forward_command_controller/ForwardCommandController

omni_chassis_controller:
  ros__parameters:
    omni_wheel_joints:
      - wheels_pid_controller/front_left_wheel_joint
      - wheels_pid_controller/front_right_wheel_joint
      - wheels_pid_controller/back_left_wheel_joint
      - wheels_pid_controller/back_right_wheel_joint

    omni_wheel_forward_angles: [0.0, 180.0, 0.0, 180.0]

    omni_wheel_center_x: [0.2, 0.2, -0.2, -0.2]
    omni_wheel_center_y: [0.2, -0.2, 0.2, -0.2]

    omni_wheel_sliding_angles: [-45.0, 45.0, 45.0, -45.0]

    omni_wheel_radius: 0.076

    control_mode: 0

    yaw_gimbal_joint: yaw_gimbal_joint

    follow_pid_gains:
      { p: 4.0, i: 2.0e-1, d: 0.0, i_clamp_max: 3.0, i_clamp_min: -3.0, antiwindup: true }

    follow_pid_target: 0.0

    reference_timeout: 0.2

wheels_pid_controller:
  ros__parameters:
    dof_names:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint

    command_interface: effort

    reference_and_state_interfaces: ["velocity"]

    gains:
      front_left_wheel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      front_right_wheel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      back_left_wheel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      back_right_wheel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }

gimbal_position_controller:
  ros__parameters:
    yaw_gimbal_joint:
      enable: true
      name: yaw_gimbal_joint

    pitch_gimbal_joint:
      enable: true
      name: pitch_gimbal_joint

    imu_topic: /imu


shoot_controller:
  ros__parameters:
    friction_wheel:
      velocity: -700.0
      inverse: false

    bullet_loader:
      velocity: 0.1

    gains:
      friction_wheel1_joint_vel2eff:
        { p: 6.0e-3, i: 0.0, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      friction_wheel2_joint_vel2eff:
        { p: 6.0e-3, i: 0.0, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      bullet_loader_joint_vel2eff:
        { p: 1.0e-1, i: 5.0e-1, d: 0.0e-2, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
        
dbus_control_node:
  ros__parameters:
    dbus_port: "tty_DBUS"

hero_vehicle:
  ros__parameters:
    enable_ros2_control: true
    aim_topic: "/gimbal_position_controller/reference"
    shoot_topic: "/shoot_controller/reference"
    control:
      trans_vel: 2.5 # m/s
      rot_vel: 3.0 # rad/s
      stick_sens: 5.00 # rad/s
      mouse_sens: 10.0
      deadzone: 0.15 # percentage
      video_link_blank_time: 0.05 # second

capacitor:
  ros__parameters:
    capacitor_device: "pacific_spirit"
    can_interface: "can_1"
referee_serial:
  ros__parameters:
    regular_link_port: "/dev/tty_REF"
    regular_link_baud: 115200
    video_link_port: "/dev/tty_VT02"
    video_link_baud: 921600
    isDebug: false
    debugUnhandledShown: false
    warningShown: false
forward_pitch_controller:
  ros__parameters:
    joints:
      - pitch_gimbal_joint
    interface_name: position
forward_yaw_controller:
  ros__parameters:
    joints:
      - yaw_gimbal_joint
    interface_name: position