controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    agv_chassis_controller:
      type: meta_chassis_controller/AgvChassisController

    wheels_pid_controller:
      type: pid_controller/PidController

    steer_pos2vel_pid_controller:
      type: pid_controller/PidController

    steer_vel2eff_pid_controller:
      type: pid_controller/PidController

    gimbal_controller:
      type: meta_gimbal_controller/GimbalController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    shoot_controller:
      type: meta_shoot_controller/ShootController

agv_chassis_controller:
  ros__parameters:
    agv_vel_joints:
      - wheels_pid_controller/left_forward_vel_joint
      - wheels_pid_controller/left_back_vel_joint
      - wheels_pid_controller/right_forward_vel_joint
      - wheels_pid_controller/right_back_vel_joint
    agv_pos_joints:
      # - steer_pos2vel_pid_controller/left_forward_pos_joint
      # - steer_pos2vel_pid_controller/left_back_pos_joint
      # - steer_pos2vel_pid_controller/right_forward_pos_joint
      # - steer_pos2vel_pid_controller/right_back_pos_joint
      - left_forward_pos_joint
      - left_back_pos_joint
      - right_forward_pos_joint
      - right_back_pos_joint

    agv_wheel_center_x: 0.225
    agv_wheel_center_y: 0.225

    agv_wheel_radius: 0.076

    control_mode: 2

    yaw_gimbal_joint: yaw_gimbal_joint

    follow_pid_gains:
      { p: 4.0, i: 2.0e-1, d: 0.0, i_clamp_max: 3.0, i_clamp_min: -3.0, antiwindup: true }

    follow_pid_target: 0.7853981634

    # steer_pos2vel_gains:
    #   { p: 45.0, i: 5.5, d: 1.0E4, i_clamp_max: 3.0, i_clamp_min: -3.0, antiwindup: true }
    # steer_vel2eff_gains:
    #   { p: 1.0, i: 35.0, d: 0.0, i_clamp_max: 3.0, i_clamp_min: -3.0, antiwindup: true }

    # steer_pos2vel_gains:
    #   # { p: 7.0, i: 0.0, d: 0.0, i_clamp_max: 3.0, i_clamp_min: -3.0, antiwindup: true }
    #   { p: 1.0, i: 0.1, d: 0.0 }
    left_forward_steer_pos2vel_gains:
      { p: 4.0, i: 0.0, d: 0.0 }
    left_back_steer_pos2vel_gains:
      { p: 4.0, i: 0.0, d: 0.0 }
    right_forward_steer_pos2vel_gains:
      { p: 4.0, i: 0.0, d: 0.0}
    right_back_steer_pos2vel_gains:
      { p: 4.0, i: 0.0, d: 0.0}

    left_forward_steer_vel2eff_gains:
      { p: 1.0e-2, i: 2.5e-1, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
    left_back_steer_vel2eff_gains:
      { p: 1.0e-2, i: 2.5e-1, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
    right_forward_steer_vel2eff_gains:
      { p: 1.0e-2, i: 2.5e-1, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
    right_back_steer_vel2eff_gains:
      { p: 1.0e-2, i: 2.5e-1, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }


    reference_timeout: 0.2

wheels_pid_controller:
  ros__parameters:
    dof_names:
      - left_forward_vel_joint
      - left_back_vel_joint
      - right_forward_vel_joint
      - right_back_vel_joint

    command_interface: effort

    reference_and_state_interfaces: ["velocity"]

    gains:
      left_forward_vel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      left_back_vel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      right_forward_vel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      right_back_vel_joint:
        { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }


# steer_vel2eff_pid_controller:
#   ros__parameters:
#     dof_names:
#       - left_forward_pos_joint
#       - left_back_pos_joint
#       - right_forward_pos_joint
#       - right_back_pos_joint

#     command_interface: effort

#     reference_and_state_interfaces: ["vel_cmd"]

#     gains:
#       left_forward_pos_joint:
#         { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
#       left_back_pos_joint:
#         { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
#       right_forward_pos_joint:
#         { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
#       right_back_pos_joint:
#         { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }

# steer_pos2vel_pid_controller:
#   ros__parameters:
#     dof_names:
#       - left_forward_pos_joint
#       - left_back_pos_joint
#       - right_forward_pos_joint
#       - right_back_pos_joint

#     command_interface: effort

#     reference_and_state_interfaces: ["position"]

#     gains:
#       left_forward_pos_joint:
#         { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
#       left_back_pos_joint:
#         { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
#       right_forward_pos_joint:
#         { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
#       right_back_pos_joint:
#         { p: 2.0e-2, i: 1.0e-4, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }         # TODO: PID parameters to finish


gimbal_controller:
  ros__parameters:
    yaw_gimbal_joint:
      enable: true
      name: yaw_gimbal_joint

    pitch_gimbal_joint:
      enable: true
      name: pitch_gimbal_joint

    imu_topic: /imu

    gains:
      yaw_gimbal_joint_pos2vel: { p: 7.0, i: 0.0, d: 0.0 }
      pitch_gimbal_joint_pos2vel: { p: 30.0, i: 0.0, d: 0.05 }
      yaw_gimbal_joint_vel2eff:
        { p: 5.0e-1, i: 2.5e-1, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      pitch_gimbal_joint_vel2eff:
        { p: 1.0e-1, i: 2.0e-2, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }

shoot_controller:
  ros__parameters:
    friction_wheel:
      velocity: -500.0
      inverse: false

    bullet_loader:
      velocity: 0.1

    gains:
      friction_wheel1_joint_vel2eff:
        { p: 6.0e-3, i: 0.0, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      friction_wheel2_joint_vel2eff:
        { p: 6.0e-3, i: 0.0, d: 0.0, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }
      bullet_loader_joint_vel2eff:
        { p: 1.0e-1, i: 5.0e-1, d: 0.0e-2, i_clamp_max: 1.0, i_clamp_min: -1.0, antiwindup: true }

dbus_control:
  ros__parameters:
    dbus_port: "dbus_control"

dbus_vehicle:
  ros__parameters:
    enable_ros2_control: true
    aim_topic: "/gimbal_controller/reference"
    shoot_topic: "/shoot_controller/reference"
    control:
      trans_vel: 2.5 # m/s
      rot_vel: 3.0 # rad/s
      stick_sens: 5.00 # rad/s
      mouse_sens: 10.0
      deadzone: 0.15 # percentage
