# This config file is used by ros2_control
# Note that, instead of using this, we choose to use meta_bringup/config/engineer26.yaml for engineer
# to keep all controllers in one file.
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    meta_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

meta_manipulator_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity